base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8_bit: true

bf16: true
strict: false

datasets:
  - path: LeeHarrold/yocto-manual-completion
    type: completion

dataset_prepared_path: /sky-notebook/yocto-dev-manual-completion-test/last_run_prepared
val_set_size: 0.05
output_dir: /sky-notebook/yocto-dev-manual-completion-test

hub_model_id: LeeHarrold/mistral-yocto-manual_test # TODO: Replace with hub model id
hf_use_auth_token: true # TODO: push as private or public model


sequence_len: 1024
sample_packing: true
pad_to_sequence_len: true

eval_sample_packing: false

adapter: qlora
lora_model_dir:
# 32 seems high. trying 16
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project: lee-axolotl-yocto-manual
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 6
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints: true ## manage check point resume from here
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

# what are these?
warmup_steps: 10
eval_steps: 0.05
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 2 ## increase based on your dataset
save_strategy: steps
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"